### ISSUE TITLE
Clusters missing

### ISSUE THREAD

**Issue by CountZero-Error** [dkim195/Ptbp1_Nature_MA#1]
Hi, I'm using the data from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE184933 to run your code, but all samples' clusters find is different from the comments in the code, it's missing some of the clusters. For example FACS Cortex, it's missing 14. Doublet and show Oligodendrocyte contamination and 15. Doublet and show Oligodendrocyte contamination. Could u please help me solve this, thank you.

**Comment by dkim195** [comment]
Hi,
The discrepancies in cluster identification are likely due to differences in R and package versions. I just repeated the step with the same versions and got the same result.  Otherwise,  those clusters are also easy to find in different package versions, although cluster names might be different.

**Comment by CountZero-Error** [comment]
Hi, due to some unknown reason I can not install some critical R packages with the version you specified in R 3.6.1. Could you please share with me the outputs for each sample. Much appreciate.
